### PR TITLE
Sorting, paging, rest of the filters and initial parts of jwt. Note API endpoints changed a little 

### PR DESCRIPTION
**Pull request by AntoineTalaat**
Wanted to rename the branch to indicate that I will handle jwt here but couldn't xD. anyway, 
I did sorting and paging and changed the API a little to do jwt authorization. just simple stuff given the close deadline.
some details will be handled when the other branches merge.

### CODE REVIEW

**Review by MarkEhab33 — COMMENTED** [review]
why DAO's  classes are commented ?

**Comment by AntoineTalaat** [comment]
> why DAO's classes are commented ?

The daos job is basically done by repos classes (which is direct access to db). daos here were assigned to access multiple tables at once and return the posts small view. me and yara decided it was best to let post service class handle these details and that this layer was redundant.

**Comment by AntoineTalaat** [comment]
I left them to warn anybody merging that they are not needed and that we should put the needed methods in post service.
if i deleted them only it would be added again I think.

**Comment by MarkEhab33** [comment]
Make sure you handle all types of Errors and Exceptions

**Pull request merged**
